### PR TITLE
Add checkbox to select (or unselect) all user sessions at once.

### LINKED ISSUE #379: User overview: select all
Is it possible to implement the function "select all" in the user overview?
At the moment (I think so!), there is no option like this. Thus, I have to select manually all participants to delete them or to send a reminder. 

If there is already such a solution, please excuse my note. 

Julia

### PR DESCRIPTION
**Pull request by mpw-wwu**
This is a suggestions to handle request #379.

@rubenarslan, I'm not sure, if you want this in develop or master.

The JavaScript-Code could be moved into a seperat <script>-section, if wanted. But it does its work so far.

The code doesn't deal with pagination. Maybe we need another button or function to delete all in database at once. But I don't see any usecase why this would be used for more than just test sessions, so I think this should do.

Closes #379

### CODE REVIEW

**Comment by mpw-wwu** [comment]
(Btw., I know, that I can merge this myself, this is just to discuss the approach and code quality.)

**Comment by rubenarslan** [comment]
The solution seems fine. I think we want just a JS selector. If people need to remind everyone, they can  use "Show all on one page" for most studies (for some it will be too much).
But it would be nice if you could move this into run.js or whatever it's called.

**Comment by mpw-wwu** [comment]
Good point. But if we place the code in run.js, it will be loaded for every survey participant.

I've just gone through the js file structure. I didn't find a js file which is only included into the admin area. 

There is webroot/assets/admin/js/main.js, but that comes with AdminLTE v2.

Did I oversee something or should we just create a js file for the admin area?

**Comment by rubenarslan** [comment]
I think you overlooked how we create formr-admin.js in https://github.com/rubenarslan/formr.org/blob/master/webroot/assets/Gruntfile.js but IDK it's been a while since  I looked into it. @cyriltata ?

**Comment by cyriltata** [comment]
Maybe this can be merged in the ongoing hotfix branch?

**Comment by mpw-wwu** [comment]
I moved @cyriltata's JQuery code to a new admin.js. Because I messed up with git rebase, my original commit got lost. But we don't need that anyway.

Ready to merge in my opinion!

We can cherry-pick this to master aswell, if you want to have it there. I don't need master at all, so I'll leave that to you.

**Comment by mpw-wwu** [comment]
@cyriltata, what's the difference between mentioning the file in the Gruntfile.js or going via the assets.json in the admin-section as I did? Do we need both or are those just two equivalent solutions?

**Comment by cyriltata** [comment]
@mpw-wwu Currently we need both.

The addition in the Gruntfile is just for linting and thinking of it, it will be easier to just read to-be-linted JS files from the config. That way we only need to list once.

**Comment by mpw-wwu** [comment]
I still don't understand what the difference would be. We have a file where to be included and to be linted files are listed (assets.json). And I don't think listing the filename twice makes any difference. The assets.json file is just an include into Gruntfile.js

It's just a design decision we have to make. Do we want everything in the Gruntfile.js or do we want the included files separate from the grunt logic. I prefer the latter, but it's not important to me.

Do you want me to remove the inclusion in assets.json?

**Comment by cyriltata** [comment]
No, keep the inclusion in assets.json
We are basing saying the same thing i.e. no need to list the assets twice. Will modify the Gruntfile to read to be linted JS files from assets.json

**Comment by cyriltata** [comment]
yes, maybe  we should add this to our soon to be released branch.

**Comment by mpw-wwu** [comment]
Sure, why not.

**Pull request merged**
