### PR TITLE
Allow sending emails without authentification.

### PR DESCRIPTION
**Pull request by mpw-wwu**
This might be relevant for setups at e. g. universities, where email sending is bind to source ip addresses and no account is required.

### CODE REVIEW

**Comment by rubenarslan** [comment]
Do you think this is a common setup? It has never been requested.. also, I wonder: isn't this less secure for the email contents for potential men-in-the-middle?

**Comment by cyriltata** [comment]
@mpw-wwu if you want to go with this then you might also need to modify the process of creating an Email Account i.e. set a couple fields optional. Then I think the best way to do it will be to add a switch in the main configuration file to turn off stmp auth for the whole formr installation instead of checking for the presence of a username. When smtp is turned off, then validation of the email account creation should change. This also entirely shifts responsibility to the hosting body.

**Comment by mpw-wwu** [comment]
We have two administrative layers of email sending. The ones for handling the signup process for the admin accounts. And the one for sending emails from within a study or run to the participants.

I wouldn't want to allow the latter to be unauthorized via the university's email server, as that might cause a SPAM problem and I don't want to handle all complains of the researchers using my instance of formR. I still want researchers to bring their own accounts.

I just changed the requirements for the email account which is configured in config/settings.php.

**Comment by cyriltata** [comment]
OK I see.. if it is upto changing only the global mail account setting this
is specific then.

best
Cyril

**Pull request merged**
