### PR TITLE
Order columns in result table by id

### PR DESCRIPTION
**Pull request by mpw-wwu**
This results in them being sorted as they were in the import sheet.

### CODE REVIEW

**Comment by rubenarslan** [comment]
No it won't, if new items are added later (they'll get higher IDs). Damn it, I thought we'd added a column for the item sheet order, but apparently I'm wrong about that. @cyriltata we should add that to the schema to faithfully reproduce what people upload.

**Comment by rubenarslan** [comment]
This might actually also lead to more substantive issues than misordered results: if an item is added to a block of items later, it won't be randomised together with that block.

**Comment by rubenarslan** [comment]
For joining with e.g. survey_item_displays. Pretty sure, it's smarter to have a separate column for the order.

**Comment by mpw-wwu** [comment]
That was a stupid idea anway, as the IDs are about all items. The items of one survey don't necessarily have continuous numbers.

What about the column survey_items.order?

**Comment by rubenarslan** [comment]
order is a reserved term in mysql. Doesn't matter if we escape it, but maybe `sheet_order` for maximal clarity?

**Comment by mpw-wwu** [comment]
There is an existing column order...

**Comment by rubenarslan** [comment]
Ok, so this is what I remembered. That's an easy fix then as I thought. Which leaves us time to solve the mystery of wtf is wrong with my eyes/brain that I looked at the schema.sql and thought it was not there :-0

**Comment by mpw-wwu** [comment]
I updated the commit. We should still test this a little, but I think we figured this out now and this solutions feels better than my hack with the id-column.

**Pull request merged**
